/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 6.5 */
/* Thu Apr 06 15:23:23 2017 */

/* parameterized module instance */
testmem1 __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), .RdClock( ), 
    .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), .Q( ));
